# Generated by Django 4.1.2 on 2022-10-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_review_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, to='projects.tag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('+', 'Ijobiy'), ('-', 'Salbiy'), ('=', 'Neytral')], max_length=50),
        ),
    ]
